# Generated by Django 4.1.6 on 2023-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('university_address', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('till_date', models.DateField()),
            ],
        ),
    ]
