# Generated by Django 4.1.6 on 2023-02-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('dete_start', models.DateField()),
                ('date_end', models.DateField()),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
