# Generated by Django 4.1.6 on 2023-02-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_documets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
