# Generated by Django 4.1.6 on 2023-02-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume_project', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_project',
            name='resume_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resume'),
        ),
    ]
